### PR TITLE
Upgrade/include .NET 6

### PR DESCRIPTION
**Pull request by robert-stratecglobal**
@JohnCampionJr 
Hi John,  Please accept this PR to include .NET 6

Please note that I did this, as in a recent project migration, I tried to use your library, and was giving binding error, pointing to MongoFramework 0.25.0.

In this PR:
1.  includes "multi-target" adjustements, added .NET6, and replace `NETCORE2.1` by `NETSTARDARD2.0`
2. multi-target testings, `NetCoreApp2.1, 3,1, NET5, NET6`.
3. Updated Samples to `NET 6` (that is why so many files)

N.B.  support for  `NetCoreApp2.1` is out of scope, please consider dropping support for it...
Other libraries like  `MongoFramwork 0.26.x` have stopped supporting it.  There minimum compatibility is `NETSTANDARD2.1`

### CODE REVIEW

**Comment by robert-stratecglobal** [comment]
Hi @JohnCampionJr,
Do you have any comments or thinks you would like to address ?
Let me know.

**Comment by JohnCampionJr** [comment]
Hi, thanks for this.  We need to update the GH workflow to test with .NET 6.0.  I'll take a look at it ASAP unless you have time.

**Comment by bobbyangers** [comment]
I can give it a try....

**Comment by robert-stratecglobal** [comment]
I sumitted a correction....  Can you release the pipeline ?

**Pull request merged**
